### ISSUE TITLE
singular matrix

### ISSUE THREAD

**Issue by YxxOvO** [Ali-Meh619/MHGphormer#1]
Because my gpu memories is not enough to run,so I have to change the args from System_Setup_and_Generating_Dataset.py,
I did these change that include
IRS_elements":4,"IRS_elements_row":2,"BS_row":1,"BS_col":2,"BS_antenna":2,"train_s":480,"validation_s":60,
"test_s":60,"samples":600,"batch":32,
the other are same of you.
at last it runs error,how to solve it:
rate_f=torch.log2(torch.linalg.det(I_r+torch.einsum('bsiurt,bsiutp->bsiurp',nu,torch.linalg.inv(de+1e-10))).real)
^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._C._LinAlgError: linalg.inv: (Batch element 600000): The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

**Comment by Ali-Meh619** [comment]
Hello,
you can add a larger value to de tensor to avoid this issue.
rate_f=torch.log2(torch.linalg.det(I_r+torch.einsum('bsiurt,bsiutp->bsiurp',nu,torch.linalg.inv(de+1e-7))).real)

you can try 1e-7 or add a diagonal matrix multiplied by 1e-7.

**Comment by YxxOvO** [comment]
> Hello, you can add a larger value to de tensor to avoid this issue. rate_f=torch.log2(torch.linalg.det(I_r+torch.einsum('bsiurt,bsiutp->bsiurp',nu,torch.linalg.inv(de+1e-7))).real)
> 
> you can try 1e-7 or add a diagonal matrix multiplied by 1e-7.

I'm glad to receive your messages,I try another way to solve this problem.
It's rate_f=torch.log2(torch.linalg.det(I_r+torch.einsum('bsiurt,bsiutp->bsiurp',nu,torch.linalg.pinv(de+1e-10))).real+1e-5) 
How do u think this way,I did this will cause other mistakes?

**Comment by Ali-Meh619** [comment]
The correct way is to add a value like 1e-7 inside the torch.linalg.pinv in order to avoid singular value issue, this would help
